spring:
  ##数据库连接设置
  datasource:
    #可执行程序的当前路径
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    #指定的静态配置路径
    username: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    enabled: false
  sql:
    init:
      continue-on-error: on
      platform: h2
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true